### ISSUE TITLE
Lab 2.1 Issues

### ISSUE THREAD

**Issue by ryananicholson** [sans-blue-team/sec555-mdwiki-v1#4]
Warning and Error messages in Kibana:
![image](https://user-images.githubusercontent.com/13158109/87314318-0b104700-c4f1-11ea-9da9-da2904dbd87c.png)

**Comment by ryananicholson** [comment]
Does not impact lab, ultimately, but student may think something is wrong.

**Comment by SMAPPER** [comment]
Warned users for now. In a future update I will upgrade Kibana and this goes away.
