### ISSUE TITLE
Lab 2.3 Typos

### ISSUE THREAD

**Issue by ryananicholson** [sans-blue-team/sec555-mdwiki-v1#5]
## Missing Fields

- Formatting

![image](https://user-images.githubusercontent.com/13158109/87320312-c9839a00-c4f8-11ea-8d03-cfa00e5c8286.png)

## Frequency Analysis

- Formatting

![image](https://user-images.githubusercontent.com/13158109/87320245-b4a70680-c4f8-11ea-9b6d-5260d1a57b65.png)

**Comment by SMAPPER** [comment]
Fixed
